baseURL = 'https://sksg.github.io/codespeak/'
languageCode = 'en-us'
title = 'Sørens Code|Speak'

theme = "gruvhugo"

defaultExtension = "html"
metaDataFormat = "toml"


[taxonomies]
  tag      = "tags"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about"

  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "post/"

  [[menu.main]]
    identifier = "tags"
    name       = "Tags"
    url        = "tags/"

[params.main]
  enabled = true
  headerTitle = "Sørens Code|Speak"
  img = "images/front_small.jpg"
  # img_title = ""
  description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam. Quis risus sed vulputate odio ut. Sed turpis tincidunt id aliquet risus feugiat in ante metus. Bibendum at varius vel pharetra vel turpis. Semper viverra nam libero justo laoreet sit amet cursus. Mauris a diam maecenas sed enim ut sem."

  [[params.social]]
    name = "github"
    url  = "https://github.com/sksg"

  [[params.social]]
    name = "email"
    url  = "https://github.com/sksg/codespeak/discussions/new?category=q-a"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/sksg/"

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = true
    style = 'swapoff'
    tabWidth = 4